# Task - 3 => DONE by Azizbek

# 	ComboBox orqali Tug'ilgan viloyatini, Tuman yoki shaharni, 
# 	Jinsini va Millatini tanlasin va Barcha tanlangan haqida ma'lumot(MessageBoxda) chiqarilsin.

import os
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
os.system("clear")

class ilova(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Ma'lumotnoma")
        self.setFont(QFont("Times New Roman",24))
        self.setGeometry(100, 100, 600, 400)

        layout = QVBoxLayout()

        self.province_label = QLabel("Tug'ilgan viloyat:", self)
        self.province_combo = QComboBox(self)
        self.province_combo.addItem("Toshkent")
        self.province_combo.addItem("Toshkent Vil.")
        self.province_combo.addItem("Samarqand")
        self.province_combo.addItem("Farg'ona")
        self.province_combo.addItem("Namangan")
        self.province_combo.addItem("Qashqadaryo")
        self.province_combo.addItem("Surxondaryo")
        self.province_combo.addItem("Buxoro")
        self.province_combo.addItem("Xorazm")
        self.province_combo.addItem("Navoiy")
        self.province_combo.addItem("Andijon")
        self.province_combo.addItem("Sirdaryo")
        self.province_combo.addItem("Qoraqalpog'iston Res.")
        self.province_combo.currentIndexChanged.connect(self.update_districts)

        self.district_label = QLabel("Tuman:", self)
        self.district_combo = QComboBox(self)

        self.gender_label = QLabel("Jinsi:", self)
        self.gender_combo = QComboBox(self)
        self.gender_combo.addItem("Erkak")
        self.gender_combo.addItem("Ayol")

        self.nationality_label = QLabel("Millati:", self)
        self.nationality_combo = QComboBox(self)
        self.nationality_combo.addItem("O'zbek")
        self.nationality_combo.addItem("Qirg'iz")
        self.nationality_combo.addItem("Tojik")
        self.nationality_combo.addItem("Qozoq")
        self.nationality_combo.addItem("Arman")
        self.nationality_combo.addItem("Rus")
        self.nationality_combo.addItem("Tatar")
        self.nationality_combo.addItem("Qoraqalpoq")
        self.nationality_combo.addItem("Uyg'ur")
        self.nationality_combo.addItem("Yevrey")

        self.submit_button = QPushButton("Ma'lumotni ko'rish", self)
        self.submit_button.clicked.connect(self.show_info)

        layout.addWidget(self.province_label)
        layout.addWidget(self.province_combo)
        layout.addWidget(self.district_label)
        layout.addWidget(self.district_combo)
        layout.addWidget(self.gender_label)
        layout.addWidget(self.gender_combo)
        layout.addWidget(self.nationality_label)
        layout.addWidget(self.nationality_combo)
        layout.addWidget(self.submit_button)

        self.setLayout(layout)

    def update_districts(self, index):
        self.district_combo.clear()
        selected_province = self.province_combo.currentText()
        if selected_province == "Toshkent":
            self.district_combo.addItem("Bekemir")
            self.district_combo.addItem("Sergeli")
            self.district_combo.addItem("Mirobod")
            self.district_combo.addItem("Uchtepa")
            self.district_combo.addItem("Yakkasaroy")
            self.district_combo.addItem("Yunusobod")
            self.district_combo.addItem("Shayxontohur")
            self.district_combo.addItem("Mirzo Ulug'bek")
            self.district_combo.addItem("Chilonzor")
            self.district_combo.addItem("Olmazor")
        elif selected_province == "Toshkent Vil.":
            self.district_combo.addItem("Bostanliq")
            self.district_combo.addItem("Piskent")
            self.district_combo.addItem("Zangiota")
            self.district_combo.addItem("Zafar")
            self.district_combo.addItem("Angren")
            self.district_combo.addItem("Yangi yo'l")
            self.district_combo.addItem("Chinoz")
            self.district_combo.addItem("Parkent")
            self.district_combo.addItem("Chirchiq")
            self.district_combo.addItem("G'azalkent")
        elif selected_province == "Samarqand":
            self.district_combo.addItem("Urgut")
            self.district_combo.addItem("Jomboy")
            self.district_combo.addItem("Nurobod")
            self.district_combo.addItem("Narpay") 
            self.district_combo.addItem("Aloviddin")
            self.district_combo.addItem("Ishtixon")
            self.district_combo.addItem("Mirzo Ulug'bek")
            self.district_combo.addItem("Payariq")
            self.district_combo.addItem("Oqdaryo")
            self.district_combo.addItem("Konimex")
        elif selected_province == "Farg'ona":
            self.district_combo.addItem("Beshariq")
            self.district_combo.addItem("Oltiariq")
            self.district_combo.addItem("Quva")
            self.district_combo.addItem("Sux") 
            self.district_combo.addItem("Bog'don")
            self.district_combo.addItem("Dang'ara")
            self.district_combo.addItem("Furqat")
            self.district_combo.addItem("Marg'ilon")
            self.district_combo.addItem("G'ishton")
            self.district_combo.addItem("Toshloq")            
        elif selected_province == "Namangan":
            self.district_combo.addItem("Norin")
            self.district_combo.addItem("Pop")
            self.district_combo.addItem("Chust")
            self.district_combo.addItem("Uychi") 
            self.district_combo.addItem("Chortoq")  
            self.district_combo.addItem("Ko'sonsoy")  
            self.district_combo.addItem("To'raqorg'on")   
        elif selected_province == "Qashqadaryo":
            self.district_combo.addItem("Qarshi")
            self.district_combo.addItem("Kitob")
            self.district_combo.addItem("Yakkabog'")
            self.district_combo.addItem("Shaxrisabiz")
            self.district_combo.addItem("Chiroqchi")
            self.district_combo.addItem("Dexqonobod")
            self.district_combo.addItem("G'o'zor")
            self.district_combo.addItem("Mirshikor")
            self.district_combo.addItem("Muborak")
            self.district_combo.addItem("Nishon")
            self.district_combo.addItem("Qamashi")              
        elif selected_province == "Surxondaryo":
            self.district_combo.addItem("Boysun")
            self.district_combo.addItem("Denov")
            self.district_combo.addItem("Sherobod")
            self.district_combo.addItem("Oltin Soy") 
            self.district_combo.addItem("Jarqo'rg'on")  
            self.district_combo.addItem("Qumqo'rg'on")  
            self.district_combo.addItem("Saraosiyo")  
            self.district_combo.addItem("Sho'rchi")
            self.district_combo.addItem("Qiziriq")
            self.district_combo.addItem("Uzun")        
        elif selected_province == "Buxoro":
            self.district_combo.addItem("Olot")
            self.district_combo.addItem("G'ijdivon")
            self.district_combo.addItem("Jondor")
            self.district_combo.addItem("Kogon")
            self.district_combo.addItem("Karmana")  
            self.district_combo.addItem("Peshku")  
            self.district_combo.addItem("Romitan")
            self.district_combo.addItem("Shofirkon")
            self.district_combo.addItem("Vobkent")
            self.district_combo.addItem("Buzuna")        
        elif selected_province == "Xorazm":
            self.district_combo.addItem("Xiva")
            self.district_combo.addItem("Xonqa")
            self.district_combo.addItem("Gurlan")
            self.district_combo.addItem("To'rtko'l")
            self.district_combo.addItem("Qo'g'irot")
            self.district_combo.addItem("Shovot")
            self.district_combo.addItem("Gurlan")
            self.district_combo.addItem("Qoshko'pir")
            self.district_combo.addItem("Yangiariq")
            self.district_combo.addItem("Hazorasp")
            self.district_combo.addItem("Qo'rg'ontepa")
            self.district_combo.addItem("Yangi Bozor")                
        elif selected_province == "Navoiy":
            self.district_combo.addItem("Xatirchi")
            self.district_combo.addItem("Nurota")
            self.district_combo.addItem("Karmana")
            self.district_combo.addItem("Qiziltepa")
            self.district_combo.addItem("Navbaxor")
            self.district_combo.addItem("Tomdi")    
        elif selected_province == "Andijon":
            self.district_combo.addItem("Baliqchi")
            self.district_combo.addItem("Bostonliq")
            self.district_combo.addItem("Buloqboshi")
            self.district_combo.addItem("Jalaquduq")
            self.district_combo.addItem("Marhamat")
            self.district_combo.addItem("Oltinko'l")
            self.district_combo.addItem("Paxtaobod")
            self.district_combo.addItem("Shaxrixon")
            self.district_combo.addItem("Xonobod")
            self.district_combo.addItem("Asaka")
            self.district_combo.addItem("Qorasuv")
            self.district_combo.addItem("Izbosgan") 
        elif selected_province == "Sirdaryo":
            self.district_combo.addItem("Guliston")
            self.district_combo.addItem("Akaltyn")
            self.district_combo.addItem("Sardorba")
            self.district_combo.addItem("Yangi yer")
            self.district_combo.addItem("Siradryo tumani")
            self.district_combo.addItem("Boyovut")
            self.district_combo.addItem("Mirzaobod") 
        elif selected_province == "Qoraqalpog'iston Res.":
            self.district_combo.addItem("Beruniy")
            self.district_combo.addItem("Kegeyli")
            self.district_combo.addItem("Mo'ynoq")
            self.district_combo.addItem("Tahiyatosh")
            self.district_combo.addItem("Qo'ng'irot")
            self.district_combo.addItem("Qorao'zak")
            self.district_combo.addItem("Shumanay")
            self.district_combo.addItem("Tahiyatosh")
            self.district_combo.addItem("Tortko'l")
            self.district_combo.addItem("Xo'jayli")
            self.district_combo.addItem("Xonqa")
            self.district_combo.addItem("Ellikqala")       

    def show_info(self):
        viloyat = self.province_combo.currentText()
        tuman = self.district_combo.currentText()
        jins = self.gender_combo.currentText()
        millat = self.nationality_combo.currentText()

        info_text = f"Tug'ilgan viloyat: {viloyat}\nTuman yoki shahar: {tuman}\nJinsi: {jins}\nMillati: {millat}"
        QMessageBox.information(self, "Citizen Information", info_text)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = ilova()
    window.show()
    sys.exit(app.exec_())