A = str(int(input("Son : ")))
match (A):
    case "1" : print("Winter")
    case "2" : print("Winter")
    case "3" : print("Spring")
    case "4" : print("Spring")
    case "5" : print("Spring")
    case "6" : print("Summer")
    case "7" : print("Summer")
    case "8" : print("Summer")
    case "9" : print("Autumn")
    case "10" : print("Autumn")
    case "11" : print("Autumn")
    case "12" : print("Winter")
